### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jjpe** [maartentbm/ContextPL1#19]
Hi team 1,

I have feedback ready for you. What email address(es) should I send it to?

Cheers,
Joey

**Comment by maartentbm** [comment]
C.S.Yu@student.tudelft.nl; J.R.T.E.vanderHout@student.tudelft.nl; M.Pasterkamp@student.tudelft.nl; M.M.vanderWel@student.tudelft.nl; M.H.Flikkema@student.tudelft.nl
